/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualanikan;

import java.awt.Color;
import java.awt.Cursor;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MFD7
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    
    int indvarHistory = 1;
    int indvarUpdate = 0;
    int indvarUangmasuk = 0;
    String value4;
    
    
    public Admin() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Ikan");
        javax.swing.ImageIcon ic = new javax.swing.ImageIcon(getClass().getResource("/images/ikan.png"));
        this.setIconImage(ic.getImage());
        
        btnHistory.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnUpdate.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnUangmasuk.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jLabel1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jPanel5.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jPanel1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jPanel6.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnHapus.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        
        tableQuery();
        tableQuery1();
        tableQuery2();
        tableQuery3();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnHistory = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        indHistory = new javax.swing.JPanel();
        btnUangmasuk = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        indUangmasuk = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        indUpdate = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        contentPanel = new javax.swing.JPanel();
        panelHistory = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        dateChooserdelete = new com.toedter.calendar.JDateChooser();
        btnHapus = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelUpdate = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        textJenis = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textHarga = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textStock = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textTambah = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        textTotal = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        panelUangmasuk = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        dateChooseru = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        textUangmasuk = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(78, 109, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Delete_30px.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 30, 30));

        btnHistory.setBackground(new java.awt.Color(78, 109, 255));
        btnHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHistoryMouseExited(evt);
            }
        });
        btnHistory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("History");
        btnHistory.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        indHistory.setBackground(new java.awt.Color(78, 197, 249));

        javax.swing.GroupLayout indHistoryLayout = new javax.swing.GroupLayout(indHistory);
        indHistory.setLayout(indHistoryLayout);
        indHistoryLayout.setHorizontalGroup(
            indHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        indHistoryLayout.setVerticalGroup(
            indHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        btnHistory.add(indHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 10));

        header.add(btnHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 40));

        btnUangmasuk.setBackground(new java.awt.Color(78, 109, 255));
        btnUangmasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUangmasukMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUangmasukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUangmasukMouseExited(evt);
            }
        });
        btnUangmasuk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Uang Masuk");
        btnUangmasuk.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        indUangmasuk.setBackground(new java.awt.Color(78, 109, 255));

        javax.swing.GroupLayout indUangmasukLayout = new javax.swing.GroupLayout(indUangmasuk);
        indUangmasuk.setLayout(indUangmasukLayout);
        indUangmasukLayout.setHorizontalGroup(
            indUangmasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        indUangmasukLayout.setVerticalGroup(
            indUangmasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        btnUangmasuk.add(indUangmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 120, 10));

        header.add(btnUangmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 120, 40));

        btnUpdate.setBackground(new java.awt.Color(78, 109, 255));
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateMouseExited(evt);
            }
        });
        btnUpdate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Update");
        btnUpdate.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        indUpdate.setBackground(new java.awt.Color(78, 109, 255));

        javax.swing.GroupLayout indUpdateLayout = new javax.swing.GroupLayout(indUpdate);
        indUpdate.setLayout(indUpdateLayout);
        indUpdateLayout.setHorizontalGroup(
            indUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        indUpdateLayout.setVerticalGroup(
            indUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        btnUpdate.add(indUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 10));

        header.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 100, 40));

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 50));

        jPanel2.setBackground(new java.awt.Color(78, 109, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 10, 420));

        jPanel4.setBackground(new java.awt.Color(78, 109, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 810, 10));

        contentPanel.setLayout(new java.awt.CardLayout());

        panelHistory.setBackground(new java.awt.Color(255, 255, 255));
        panelHistory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        panelHistory.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 669, 170));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Lunas");
        panelHistory.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 130, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Belum Lunas");
        panelHistory.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 120, 30));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        panelHistory.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 800, 180));

        jPanel3.setBackground(new java.awt.Color(78, 109, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        panelHistory.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, -1, -1));

        dateChooserdelete.setBackground(new java.awt.Color(255, 255, 255));
        dateChooserdelete.setDateFormatString("d MMMMM, y");
        panelHistory.add(dateChooserdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 130, 40));

        btnHapus.setBackground(new java.awt.Color(255, 0, 0));
        btnHapus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Hapus");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        btnHapus.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 40));

        panelHistory.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, 110, 40));

        contentPanel.add(panelHistory, "card2");

        panelUpdate.setBackground(new java.awt.Color(255, 255, 255));
        panelUpdate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(null);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        panelUpdate.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 180));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Jenis Ikan :");
        panelUpdate.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 90, 40));

        textJenis.setEditable(false);
        textJenis.setBackground(new java.awt.Color(255, 255, 255));
        textJenis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panelUpdate.add(textJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 130, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Harga :");
        panelUpdate.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 90, 40));

        textHarga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panelUpdate.add(textHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 130, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Stok :");
        panelUpdate.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 90, 40));

        textStock.setEditable(false);
        textStock.setBackground(new java.awt.Color(255, 255, 255));
        textStock.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panelUpdate.add(textStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 130, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("+");
        panelUpdate.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 40, 40));

        textTambah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textTambah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textTambahKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textTambahKeyTyped(evt);
            }
        });
        panelUpdate.add(textTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 80, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("=");
        panelUpdate.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 20, 40));

        textTotal.setEditable(false);
        textTotal.setBackground(new java.awt.Color(255, 255, 255));
        textTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panelUpdate.add(textTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 70, 40));

        jPanel1.setBackground(new java.awt.Color(78, 109, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Update Stok");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 40));

        panelUpdate.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 90, 40));

        jPanel5.setBackground(new java.awt.Color(78, 109, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Update Harga");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 40));

        panelUpdate.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 90, 40));

        jPanel6.setBackground(new java.awt.Color(78, 109, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Tambah Ikan");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 40));

        panelUpdate.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 90, 40));

        contentPanel.add(panelUpdate, "card3");

        panelUangmasuk.setBackground(new java.awt.Color(255, 255, 255));
        panelUangmasuk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setBorder(null);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        panelUangmasuk.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 320));

        dateChooseru.setBackground(new java.awt.Color(255, 255, 255));
        dateChooseru.setDateFormatString("dd MMMMM, yyyy");
        dateChooseru.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateChooseruPropertyChange(evt);
            }
        });
        panelUangmasuk.add(dateChooseru, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 160, 40));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Uang Masuk :");
        panelUangmasuk.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 100, 40));

        textUangmasuk.setEditable(false);
        textUangmasuk.setBackground(new java.awt.Color(255, 255, 255));
        textUangmasuk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panelUangmasuk.add(textUangmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 210, 40));

        contentPanel.add(panelUangmasuk, "card4");

        getContentPane().add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 810, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistoryMouseEntered
        setpaneColor(btnHistory);
        setindColor(indHistory);
    }//GEN-LAST:event_btnHistoryMouseEntered

    private void btnHistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistoryMouseExited
        if(indvarHistory==0){
            resetpaneColor(new JPanel[]{indHistory});
            
        }
        resetpaneColor(new JPanel[]{btnHistory});
    }//GEN-LAST:event_btnHistoryMouseExited

    private void btnUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseEntered
        setpaneColor(btnUpdate);
        setindColor(indUpdate);
    }//GEN-LAST:event_btnUpdateMouseEntered

    private void btnUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseExited
        if(indvarUpdate==0){
            resetindColor(new JPanel[]{indUpdate});
            
        }
        resetpaneColor(new JPanel[]{btnUpdate});
    }//GEN-LAST:event_btnUpdateMouseExited
    
    int xx, xy;
    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_headerMouseDragged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Dashboard db = new Dashboard();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        indvarUpdate = 1;
        indvarHistory = 0;
        indvarUangmasuk = 0;
        
        setindColor(indUpdate);
        resetindColor(new JPanel[]{indHistory, indUangmasuk});
        
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();
        contentPanel.add(panelUpdate);
        contentPanel.repaint();
        contentPanel.revalidate();
        tableQuery2();
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistoryMouseClicked
        indvarHistory = 1;
        indvarUpdate = 0;
        indvarUangmasuk = 0;
        
        setindColor(indHistory);
        resetindColor(new JPanel[]{indUpdate, indUangmasuk});
        
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();
        contentPanel.add(panelHistory);
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_btnHistoryMouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        int column = 1;
        int rows[]=this.jTable3.getSelectedRows();

        for(int i=0;i<rows.length;i++)
        {
            int modelRow = jTable3.convertRowIndexToModel(rows[i]);
            String value = jTable3.getModel().getValueAt(modelRow, column).toString();
            textJenis.setText(value);
            String value2 = jTable3.getModel().getValueAt(modelRow, 2).toString();
            textHarga.setText(value2);
            String value3 = jTable3.getModel().getValueAt(modelRow, 3).toString();
            textStock.setText(value3);
            value4 = jTable3.getModel().getValueAt(modelRow, 0).toString();
        }  
        
    }//GEN-LAST:event_jTable3MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        if(textHarga.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Isi harga yang ingin di update!");
        }else{
            try{
                Statement st = ConnectionManager.logOn().createStatement();
                int rs = st.executeUpdate("update ikan set harga = "+textHarga.getText()+" where id_jenis = "+value4);
                JOptionPane.showMessageDialog(null, "Harga berhasil di update!");
                tableQuery2();
            }catch(SQLException ex){
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jLabel14MouseClicked

    private void textTambahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTambahKeyReleased
        textTotal.setText(Double.toString(Double.parseDouble(textStock.getText())+Double.parseDouble(textTambah.getText())));
    }//GEN-LAST:event_textTambahKeyReleased

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        if(textTambah.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Isi stok yang akan ditambahkan!");
        }else{
            try{
                Statement st = ConnectionManager.logOn().createStatement();
                int rs = st.executeUpdate("update ikan set stok = "+textTotal.getText()+" where id_jenis = "+value4);
                JOptionPane.showMessageDialog(null, "Stok berhasil ditambah!");
                tableQuery2();
            }catch(SQLException ex){
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void textTambahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTambahKeyTyped
        char vchar = evt.getKeyChar();
        if(Character.isLetter(vchar)&&!evt.isAltDown()){
            evt.consume();
            
        }
    }//GEN-LAST:event_textTambahKeyTyped

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        TambahIkan ti = new TambahIkan();
        ti.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void btnUangmasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUangmasukMouseClicked
        indvarHistory = 0;
        indvarUpdate = 0;
        indvarUangmasuk = 1;
        
        setindColor(indUangmasuk);
        resetindColor(new JPanel[]{indUpdate, indHistory});
        
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();
        contentPanel.add(panelUangmasuk);
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_btnUangmasukMouseClicked

    private void btnUangmasukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUangmasukMouseEntered
        setpaneColor(btnUangmasuk);
        setindColor(indUangmasuk);
    }//GEN-LAST:event_btnUangmasukMouseEntered

    private void btnUangmasukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUangmasukMouseExited
        if(indvarUangmasuk==0){
            resetpaneColor(new JPanel[]{indUangmasuk});
            
        }
        resetpaneColor(new JPanel[]{btnUangmasuk});
    }//GEN-LAST:event_btnUangmasukMouseExited

    private void dateChooseruPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateChooseruPropertyChange
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
        String d = sdf.format(dateChooseru.getDate());
        String pendapatan = "";
        NumberFormat format = NumberFormat.getCurrencyInstance(Locale.ITALY);
        int pnd = 0;
        int pnd1 = 0;
        try {
            Statement st = ConnectionManager.logOn().createStatement();
            ResultSet rs = st.executeQuery("Select sum(uang) as pendapatan from history where tanggal='"+d+"'");
            try{
                while(rs.next()){
                    pendapatan = rs.getString("pendapatan");
                    pnd = Integer.parseInt(pendapatan);
                }
            }catch(NumberFormatException nex){
                pnd = 0;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String ttl = Integer.toString(pnd);
        textUangmasuk.setText(format.format(pnd).replace("€", "Rp"));
    }//GEN-LAST:event_dateChooseruPropertyChange

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
        String d = sdf.format(dateChooserdelete.getDate());
        SimpleDateFormat sdf1 = new SimpleDateFormat("dd MMMMM, yyyy", Locale.getDefault());
        String c = sdf1.format(dateChooserdelete.getDate());
        int opt = JOptionPane.showConfirmDialog(null, "Hapus history tanggal "+c+" ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if(opt==0){
            try{
                Statement st = ConnectionManager.logOn().createStatement();
                int rs = st.executeUpdate("delete from trans_lunas where tanggal = '"+d+"'");
                JOptionPane.showMessageDialog(null, "History berhasil dihapus!");


            }catch(SQLException ex){
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        tableQuery();
        DefaultTableModel table = (DefaultTableModel)jTable1.getModel();
        table.fireTableDataChanged();
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }
    
    private void setpaneColor(JPanel pane){
        pane.setBackground(new Color(78,220,253));
    }
    
    private void resetpaneColor(JPanel [] pane){
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(78,109,255));
        }
    }
    
    private void setindColor(JPanel pane){
        pane.setBackground(new Color(78,197,249));
    }
    
    private void resetindColor(JPanel [] pane){
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(78,109,255));
        }
    }
    
    private void pendapatan(){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDate localDate = LocalDate.now();
        String tanggal = dtf.format(localDate);
        
    }
    
    private void tableQuery(){
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        String namaTrans, banyakIkan, totalIkan, idTrans, tanggal;
        
        DefaultTableModel model = new DefaultTableModel(new String[]{"Id", "Nama", "Jenis Ikan", "Banyak", "Total", "Tanggal"}, 0);
        String jns_ikan = "";
        try {
            Statement st = ConnectionManager.logOn().createStatement();
            ResultSet rs = st.executeQuery("Select * From trans_lunas, ikan where trans_lunas.id_jenis=ikan.id_jenis");
            DefaultTableModel t=(DefaultTableModel)jTable1.getModel();
            if(rs.next() == false){
                t.setRowCount(0);
            }else{
                do{
                namaTrans = rs.getString("nama");
                banyakIkan = rs.getString("banyak");
                totalIkan = rs.getString("total");
                jns_ikan = rs.getString("jenis_ikan");
                idTrans = rs.getString("id_transLunas");
                tanggal = rs.getString("tanggal");
                model.addRow(new Object[]{idTrans, namaTrans, jns_ikan, banyakIkan, totalIkan, tanggal});
                jTable1.setModel(model); 
                }while(rs.next());
            }
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        rightRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        try{
            jTable1.getColumnModel().getColumn(0).setCellRenderer(rightRenderer);
            jTable1.getColumnModel().getColumn(1).setCellRenderer(rightRenderer);
            jTable1.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
            jTable1.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
            jTable1.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
            jTable1.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
            jScrollPane1.setBackground(new Color(0,0,0,0));
            jScrollPane1.setOpaque(false);
            jScrollPane1.getViewport().setOpaque(false);
        }catch(ArrayIndexOutOfBoundsException ab){
            ;
        }
    }
    
    private void tableQuery1(){
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        String idTrans, namaTrans, banyakIkan, totalIkan, sudahIkan, tanggal;
        
        DefaultTableModel model = new DefaultTableModel(new String[]{"Id", "Nama", "Jenis Ikan", "Banyak", "Total", "Sudah Dibayar", "Kurang", "Tanggal"}, 0);
        String jns_ikan = "";
        try {
            Statement st = ConnectionManager.logOn().createStatement();
            ResultSet rs = st.executeQuery("Select * From transaksi, ikan where transaksi.id_jenis=ikan.id_jenis");
            DefaultTableModel t=(DefaultTableModel)jTable2.getModel();
            if(rs.next() == false){
                t.setRowCount(0);
            }else{
                do{
                namaTrans = rs.getString("nama");
                banyakIkan = rs.getString("banyak");
                totalIkan = rs.getString("total");
                sudahIkan = rs.getString("sdh_dibayar");
                jns_ikan = rs.getString("jenis_ikan");
                idTrans = rs.getString("id_trans");
                tanggal = rs.getString("tanggal");
                model.addRow(new Object[]{idTrans, namaTrans, jns_ikan, banyakIkan, totalIkan, sudahIkan, Integer.toString(Integer.parseInt(totalIkan)-Integer.parseInt(sudahIkan)), tanggal});
                jTable2.setModel(model); 
                }while(rs.next());
            }
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        rightRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        try{
            jTable2.getColumnModel().getColumn(0).setCellRenderer(rightRenderer);
            jTable2.getColumnModel().getColumn(1).setCellRenderer(rightRenderer);
            jTable2.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
            jTable2.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
            jTable2.getColumnModel().getColumn(4).setCellRenderer(rightRenderer);
            jTable2.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
            jTable2.getColumnModel().getColumn(6).setCellRenderer(rightRenderer);
            jTable2.getColumnModel().getColumn(7).setCellRenderer(rightRenderer);
            jScrollPane2.setBackground(new Color(0,0,0,0));
            jScrollPane2.setOpaque(false);
            jScrollPane2.getViewport().setOpaque(false);
        }catch(ArrayIndexOutOfBoundsException ab){
            ;
        }
    }
    
    private void tableQuery2(){
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        String idTrans, namaTrans, banyakIkan, totalIkan, sudahIkan, tanggal;
        
        DefaultTableModel model = new DefaultTableModel(new String[]{"Id", "Jenis Ikan", "Harga", "Stok"}, 0);
        String jns_ikan = "";
        try {
            Statement st = ConnectionManager.logOn().createStatement();
            ResultSet rs = st.executeQuery("Select * From ikan");
            DefaultTableModel t=(DefaultTableModel)jTable3.getModel();
            if(rs.next() == false){
                t.setRowCount(0);
            }else{
                do{
                jns_ikan = rs.getString("jenis_ikan");
                idTrans = rs.getString("id_jenis");
                totalIkan = rs.getString("harga");
                sudahIkan = rs.getString("stok");
                model.addRow(new Object[]{idTrans, jns_ikan, totalIkan, sudahIkan});
                jTable3.setModel(model); 
                }while(rs.next());
            }
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        rightRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        try{
            jTable3.getColumnModel().getColumn(0).setCellRenderer(rightRenderer);
            jTable3.getColumnModel().getColumn(1).setCellRenderer(rightRenderer);
            jTable3.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
            jTable3.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
            jScrollPane3.setBackground(new Color(0,0,0,0));
            jScrollPane3.setOpaque(false);
            jScrollPane3.getViewport().setOpaque(false);
        }catch(ArrayIndexOutOfBoundsException ab){
            ;
        }
    }
    
    private void tableQuery3(){
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        String id, nama, uang, tanggal;
        
        DefaultTableModel model = new DefaultTableModel(new String[]{"Id", "Nama", "Uang", "Tanggal"}, 0);
        try {
            Statement st = ConnectionManager.logOn().createStatement();
            ResultSet rs = st.executeQuery("Select * From history");
            DefaultTableModel t=(DefaultTableModel)jTable4.getModel();
            if(rs.next() == false){
                t.setRowCount(0);
            }else{
                do{
                id = rs.getString("id");
                nama = rs.getString("nama");
                uang = rs.getString("uang");
                tanggal = rs.getString("tanggal");
                model.addRow(new Object[]{id, nama, uang, tanggal});
                jTable4.setModel(model); 
                }while(rs.next());
            }
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        rightRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        try{
            jTable4.getColumnModel().getColumn(0).setCellRenderer(rightRenderer);
            jTable4.getColumnModel().getColumn(1).setCellRenderer(rightRenderer);
            jTable4.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);
            jTable4.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
            jScrollPane4.setBackground(new Color(0,0,0,0));
            jScrollPane4.setOpaque(false);
            jScrollPane4.getViewport().setOpaque(false);
        }catch(ArrayIndexOutOfBoundsException ab){
            ;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnHapus;
    private javax.swing.JPanel btnHistory;
    private javax.swing.JPanel btnUangmasuk;
    private javax.swing.JPanel btnUpdate;
    private javax.swing.JPanel contentPanel;
    private com.toedter.calendar.JDateChooser dateChooserdelete;
    private com.toedter.calendar.JDateChooser dateChooseru;
    private javax.swing.JPanel header;
    private javax.swing.JPanel indHistory;
    private javax.swing.JPanel indUangmasuk;
    private javax.swing.JPanel indUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JPanel panelHistory;
    private javax.swing.JPanel panelUangmasuk;
    private javax.swing.JPanel panelUpdate;
    private javax.swing.JTextField textHarga;
    private javax.swing.JTextField textJenis;
    private javax.swing.JTextField textStock;
    private javax.swing.JTextField textTambah;
    private javax.swing.JTextField textTotal;
    private javax.swing.JTextField textUangmasuk;
    // End of variables declaration//GEN-END:variables
}
